[tool.poetry]
name = "django-comments-xtd"
version = "2.9.5"
description = "Django Comments Framework extension app with thread support, follow up notifications and email confirmations."
authors = ["Daniela Rus Morales <danirus@eml.cc>"]

[tool.poetry.dependencies]
python = "^3"
Django = "^4"
django-contrib-comments = "^2.1"
djangorestframework = "^3.13"
six = "^1.16"
docutils = "^0.17"
django-markdown2 = "^0.3"

[tool.poetry.dev-dependencies]
coverage = "^5.5"

[build-system]
requires = ["poetry>=1.1,<1.2"]
build-backend = "poetry.masonry.api"
